VIA_ENABLE = yes
VIAL_ENABLE = yes
LTO_ENABLE = yes
EXTRAKEY_ENABLE = yes
VIAL_ENCODERS_ENABLE = yes

QMK_SETTINGS = yes
KEY_OVERRIDE_ENABLE = no

OLED_ENABLE = yes
OLED_DRIVER = SSD1306

WPM_ENABLE = yes