ifeq ($(strip $(BOTTOM_ENCODER)), yes)
    OPT_DEFS += -DBOTTOM_ENCODER
endif

VIA_ENABLE = no
VIAL_ENABLE = no
COMBO_ENABLE = yes
ENCODER_MAP_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
TAP_DANCE_ENABLE = no
