LTO_ENABLE = yes # for AVR only

ENCODER_MAP_ENABLE = yes
OLED_ENABLE = no # using OLED pads for RGB, my guy!
RGBLIGHT_DRIVER = ws2812
RGBLIGHT_ENABLE = yes

COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
TAP_DANCE_ENABLE = no
MOUSEKEY_ENABLE = yes
