// all modes
//#define CIRQUE_PINNACLE_TAP_ENABLE
//#define POINTING_DEVICE_GESTURES_SCROLL_ENABLE
//#define CIRQUE_PINNACLE_TAPPING_TERM 200

// absolute mode
// #define CIRQUE_PINNACLE_POSITION_MODE CIRQUE_PINNACLE_ABSOLUTE_MODE
// #define POINTING_DEVICE_GESTURES_CURSOR_GLIDE_ENABLE

// relative mode
// #define CIRQUE_PINNACLE_POSITION_MODE CIRQUE_PINNACLE_RELATIVE_MODE
// #define CIRQUE_PINNACLE_SECONDARY_TAP_ENABLE // only available in relative mode
